### ISSUE TITLE
db.authenticate not supported in 3.x drivers

### ISSUE THREAD

**Issue by robmoore** [qos-ch/logback-contrib#12]
The approach used in MongoDBAppenderBase of using the deprecated `authenticate` method does not work with 3.x drivers. 

The [documentation](http://mongodb.github.io/mongo-java-driver/3.0/driver/reference/connecting/authenticating/#default-authentication-mechanism) suggests using one of two approaches. The recommended approach is also the simplest which uses the credentials in the MongoClientURI. This appears to require using MongoClient as well which is preferred as well since `Mongo.getDB` is deprecated in 3.x.

**Comment by robmoore** [comment]
Merged by @tony19 in 1.5 release.

**Comment by robmoore** [comment]
@tony19 Just curious when this release will go out.

**Comment by tony19** [comment]
@robmoore I'll try to get to it this weekend. There's an artifact-signing issue that's preventing me from deploying to Sonatype.

**Comment by ceki** [comment]
@tony19 Please let me know when you wish to do the release and I'll do it for you.

**Comment by tony19** [comment]
@ceki Thanks. I indeed have permissions to deploy, as I've done it for previous releases. The exact symptom is that the artifacts are being uploaded to Sonatype without signatures. The cause is either in my environment (I've reformatted my machine since the last release), or in the commands I'm using to release. I'll need time to investigate. If I don't get it resolved by this weekend, I may need to lean on you. 😉

**Comment by tony19** [comment]
0.1.5 is now deployed

**Comment by ceki** [comment]
Great. Csn you please send a short announcement message ti announce at qos dot ch? Are you familiar with that mailing list? It is moderated and your msg will be held up until approval.

**Comment by tony19** [comment]
Ok done
